# ---------------------------------------------------------------------------- #
# Dataset cfgs
# ---------------------------------------------------------------------------- #
dataset:
  common:
    NAME: ScanObjectNNHardest
    data_dir: './data/h5_files/main_split'
  train:
    split: train
  val:
    split: val
    num_points: 1024 

num_points: 1024  # the number of points passed into model
num_classes: &nclass
  15

feature_keys: pos

datatransforms:
  train: [PointsToTensor, PointCloudScaling, PointCloudCenterAndNormalize, PointCloudRotation]
  vote: [PointCloudRotation]
  val: [PointsToTensor, PointCloudCenterAndNormalize]
  kwargs:
    scale: [0.9, 1.1]
    angle: [0.0, 1.0, 0.0]
    gravity_dim: 1
    normalize: False

batch_size: 32
val_batch_size: 64 
dataloader:
  num_workers: 6

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
criterion_args:
  NAME: CrossEntropy
  label_smoothing: 0.0

lr: 5.0e-4 
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05

sched: cosine
epochs: 300
warmup_epochs: 10
min_lr: 1.0e-6
grad_norm_clip: 10

# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
print_freq: 10
val_freq: 1
# ----------------- Model related
log_dir: log/scanobject/Any2Point
wandb:
  project: Any2Point-ScanObjectNN-DINOV2
